### ISSUE TITLE
Priority 1.6: write a story on the rolled dice

### ISSUE THREAD

**Issue by BNRABAA** [sduoase/STAR_DICES#20]
As a writer 

I want to write a story on the rolled dice 

So that I can post it 

Priority1.6

**Comment by sduoase** [comment]
To recap today's discussion: when a user rolls the dice and tries to write a story we create an unpublished (i.e. not accessible by other users) entry in the Story database table containing the dice roll outcome. From this points onwards, until the user publishes a story with that roll, we will just retrieve this roll instead of rolling again.

**Comment by Gr3gbug** [comment]
See https://github.com/sduoase/STAR_DICES/pull/67.
