### ISSUE TITLE
Priority3.5: see a list of recent stories based on my interest

### ISSUE THREAD

**Issue by Gr3gbug** [sduoase/STAR_DICES#21]

**Comment by sduoase** [comment]
I would suggest to implement this one as 2nd priority 3 user story.

We can basically reutilize the /stories endpoint but, instead of feeding all the stories in chronological order, we can come up with some database query (e.g. all stories from followers + top 10 stories according to some rank function).

**Comment by Alepacox** [comment]
See https://github.com/sduoase/STAR_DICES/pull/80
